// 北海道 観光地データ
// region: doo(道央) / donan(道南) / doto(道東) / dohoku(道北)
// category: nature / city / hotspring / food / culture / season

const SPOTS = [
  // ===== 道央 (Doo) =====
  {
    id: 'sapporo-clock-tower',
    name: '札幌市時計台',
    nameEn: 'Sapporo Clock Tower',
    region: 'doo',
    area: '札幌',
    categories: ['culture', 'city'],
    icon: 'clock',
    color: '#FFD6E0',
    description: '札幌のシンボルとして親しまれている、明治時代に建てられた美しい時計台。重要文化財にも指定されています。',
    bestSeason: '通年',
    accessTime: 'JR札幌駅から徒歩約10分'
  },
  {
    id: 'sapporo-tv-tower',
    name: 'さっぽろテレビ塔',
    nameEn: 'Sapporo TV Tower',
    region: 'doo',
    area: '札幌',
    categories: ['city'],
    icon: 'tower',
    color: '#FFE5B4',
    description: '大通公園のシンボル。展望台からは札幌の街並みを一望でき、夜景も絶景です。',
    bestSeason: '通年',
    accessTime: '地下鉄大通駅から徒歩1分'
  },
  {
    id: 'odori-park',
    name: '大通公園',
    nameEn: 'Odori Park',
    region: 'doo',
    area: '札幌',
    categories: ['city', 'season'],
    icon: 'park',
    color: '#B5E2C5',
    description: '札幌中心部を東西に伸びる細長い公園。雪まつりやライラックまつりなど四季折々のイベントが楽しめます。',
    bestSeason: '通年',
    accessTime: '地下鉄大通駅すぐ'
  },
  {
    id: 'hokkaido-shrine',
    name: '北海道神宮',
    nameEn: 'Hokkaido Shrine',
    region: 'doo',
    area: '札幌',
    categories: ['culture'],
    icon: 'torii',
    color: '#FFD6E0',
    description: '北海道開拓の守り神を祀る神社。春には桜と梅が同時に咲き誇る花の名所です。',
    bestSeason: '春',
    accessTime: '地下鉄円山公園駅から徒歩15分'
  },
  {
    id: 'moerenuma-park',
    name: 'モエレ沼公園',
    nameEn: 'Moerenuma Park',
    region: 'doo',
    area: '札幌',
    categories: ['nature', 'culture'],
    icon: 'pyramid',
    color: '#B8E0F5',
    description: '彫刻家イサム・ノグチが基本設計した広大な公園。ガラスのピラミッドや幾何学的な造形が美しい。',
    bestSeason: '春〜秋',
    accessTime: '地下鉄環状通東駅からバス約25分'
  },
  {
    id: 'shiroi-koibito-park',
    name: '白い恋人パーク',
    nameEn: 'Shiroi Koibito Park',
    region: 'doo',
    area: '札幌',
    categories: ['food', 'culture'],
    icon: 'cookie',
    color: '#FFE5B4',
    description: '北海道銘菓「白い恋人」の工場見学やお菓子作り体験ができるテーマパーク。',
    bestSeason: '通年',
    accessTime: '地下鉄宮の沢駅から徒歩7分'
  },
  {
    id: 'maruyama-zoo',
    name: '円山動物園',
    nameEn: 'Maruyama Zoo',
    region: 'doo',
    area: '札幌',
    categories: ['city'],
    icon: 'bear',
    color: '#B5E2C5',
    description: 'ホッキョクグマやレッサーパンダなど可愛らしい動物たちに出会える動物園。',
    bestSeason: '通年',
    accessTime: '地下鉄円山公園駅から徒歩15分'
  },
  {
    id: 'otaru-canal',
    name: '小樽運河',
    nameEn: 'Otaru Canal',
    region: 'doo',
    area: '小樽',
    categories: ['city', 'culture'],
    icon: 'canal',
    color: '#B8E0F5',
    description: 'レトロな倉庫群とガス灯が美しい運河。夕暮れ時のロマンチックな景色が人気。',
    bestSeason: '通年',
    accessTime: 'JR小樽駅から徒歩約8分'
  },
  {
    id: 'otaru-music-box',
    name: '小樽オルゴール堂',
    nameEn: 'Otaru Music Box Museum',
    region: 'doo',
    area: '小樽',
    categories: ['culture', 'city'],
    icon: 'music',
    color: '#D5C5E8',
    description: '世界中から集められた数万点のオルゴールが並ぶ夢の空間。蒸気時計も必見。',
    bestSeason: '通年',
    accessTime: 'JR南小樽駅から徒歩7分'
  },
  {
    id: 'yoichi-distillery',
    name: 'ニッカウヰスキー余市蒸溜所',
    nameEn: 'Nikka Whisky Yoichi Distillery',
    region: 'doo',
    area: '余市',
    categories: ['food', 'culture'],
    icon: 'bottle',
    color: '#FFE5B4',
    description: '日本のウイスキー発祥の地。石造りの蒸溜棟や試飲も楽しめます。',
    bestSeason: '通年',
    accessTime: 'JR余市駅から徒歩3分'
  },
  {
    id: 'niseko',
    name: 'ニセコ',
    nameEn: 'Niseko',
    region: 'doo',
    area: 'ニセコ',
    categories: ['nature', 'season'],
    icon: 'mountain',
    color: '#B8E0F5',
    description: '世界有数のパウダースノーで知られる国際的スキーリゾート。夏はラフティングも人気。',
    bestSeason: '冬',
    accessTime: 'JR倶知安駅から車で15分'
  },
  {
    id: 'lake-toya',
    name: '洞爺湖',
    nameEn: 'Lake Toya',
    region: 'doo',
    area: '洞爺',
    categories: ['nature', 'hotspring'],
    icon: 'lake',
    color: '#B8E0F5',
    description: 'カルデラ湖と中島が織りなす絶景。湖畔の温泉と毎晩開催される花火も魅力。',
    bestSeason: '春〜秋',
    accessTime: 'JR洞爺駅からバス約20分'
  },
  {
    id: 'showa-shinzan',
    name: '昭和新山',
    nameEn: 'Showa Shinzan',
    region: 'doo',
    area: '壮瞥',
    categories: ['nature'],
    icon: 'volcano',
    color: '#FFD6E0',
    description: '1944年の噴火で誕生した活火山。今もなお白い噴煙を上げる特別天然記念物。',
    bestSeason: '通年',
    accessTime: 'JR洞爺駅からバス約45分'
  },
  {
    id: 'noboribetsu-onsen',
    name: '登別温泉',
    nameEn: 'Noboribetsu Onsen',
    region: 'doo',
    area: '登別',
    categories: ['hotspring', 'nature'],
    icon: 'onsen',
    color: '#FFD6E0',
    description: '9種類もの泉質を誇る日本屈指の温泉郷。地獄谷の自然美と湯けむりが魅力。',
    bestSeason: '通年',
    accessTime: 'JR登別駅からバス約15分'
  },
  {
    id: 'jigokudani',
    name: '地獄谷',
    nameEn: 'Jigokudani (Hell Valley)',
    region: 'doo',
    area: '登別',
    categories: ['nature', 'hotspring'],
    icon: 'steam',
    color: '#FFE5B4',
    description: '直径約450mの爆裂火口跡。荒々しい岩肌から立ち上る湯けむりは圧巻。',
    bestSeason: '通年',
    accessTime: '登別温泉バスターミナルから徒歩10分'
  },
  {
    id: 'lake-shikotsu',
    name: '支笏湖',
    nameEn: 'Lake Shikotsu',
    region: 'doo',
    area: '千歳',
    categories: ['nature'],
    icon: 'lake',
    color: '#B8E0F5',
    description: '日本屈指の水質を誇るカルデラ湖。透明度が高く神秘的な「支笏湖ブルー」が魅力。',
    bestSeason: '春〜秋',
    accessTime: 'JR千歳駅からバス約45分'
  },
  {
    id: 'furano-lavender',
    name: 'ファーム富田',
    nameEn: 'Farm Tomita',
    region: 'doo',
    area: '富良野',
    categories: ['nature', 'season'],
    icon: 'flower',
    color: '#D5C5E8',
    description: '7月に見頃を迎えるラベンダー畑。紫の絨毯が広がる景色は北海道の夏の象徴。',
    bestSeason: '夏',
    accessTime: 'JR中富良野駅から徒歩約25分'
  },
  {
    id: 'furano',
    name: '富良野',
    nameEn: 'Furano',
    region: 'doo',
    area: '富良野',
    categories: ['nature', 'season', 'food'],
    icon: 'flower',
    color: '#D5C5E8',
    description: 'ドラマ「北の国から」の舞台。花畑、ワイン、チーズ工房など魅力たっぷり。',
    bestSeason: '夏',
    accessTime: 'JR富良野駅周辺'
  },
  {
    id: 'biei-blue-pond',
    name: '青い池',
    nameEn: 'Blue Pond (Aoi-Ike)',
    region: 'doo',
    area: '美瑛',
    categories: ['nature'],
    icon: 'pond',
    color: '#B8E0F5',
    description: 'コバルトブルーに輝く幻想的な池。Apple社のMac壁紙にも採用された絶景。',
    bestSeason: '春〜秋',
    accessTime: 'JR美瑛駅からバス約20分'
  },
  {
    id: 'biei-patchwork',
    name: 'パッチワークの路',
    nameEn: 'Patchwork Road',
    region: 'doo',
    area: '美瑛',
    categories: ['nature', 'season'],
    icon: 'hill',
    color: '#B5E2C5',
    description: '美瑛の丘陵地帯に広がる色とりどりの畑。CMにもなった「セブンスターの木」が有名。',
    bestSeason: '夏',
    accessTime: 'JR美瑛駅から車で10分'
  },
  {
    id: 'shirahige-falls',
    name: '白ひげの滝',
    nameEn: 'Shirahige Falls',
    region: 'doo',
    area: '美瑛',
    categories: ['nature'],
    icon: 'waterfall',
    color: '#B8E0F5',
    description: '岩の隙間から湧き出るブルーリバーが流れ込む幻想的な滝。冬のライトアップも美しい。',
    bestSeason: '通年',
    accessTime: 'JR美瑛駅から車で約30分'
  },
  {
    id: 'sapporo-snow-festival',
    name: 'さっぽろ雪まつり',
    nameEn: 'Sapporo Snow Festival',
    region: 'doo',
    area: '札幌',
    categories: ['season', 'culture'],
    icon: 'snowflake',
    color: '#B8E0F5',
    description: '毎年2月に開催される世界的に有名な雪と氷の祭典。巨大な雪像が街を彩ります。',
    bestSeason: '冬',
    accessTime: '大通公園・すすきの・つどーむ'
  },

  // ===== 道南 (Donan) =====
  {
    id: 'mt-hakodate',
    name: '函館山',
    nameEn: 'Mt. Hakodate',
    region: 'donan',
    area: '函館',
    categories: ['nature', 'city'],
    icon: 'nightview',
    color: '#D5C5E8',
    description: '世界三大夜景に数えられる函館の絶景。扇形に広がるきらめく夜景は息をのむ美しさ。',
    bestSeason: '通年',
    accessTime: 'ロープウェイ約3分'
  },
  {
    id: 'goryokaku',
    name: '五稜郭',
    nameEn: 'Goryokaku',
    region: 'donan',
    area: '函館',
    categories: ['culture', 'season'],
    icon: 'star',
    color: '#FFD6E0',
    description: '星形の城郭が美しい特別史跡。春には約1,600本の桜が咲き誇る花見の名所。',
    bestSeason: '春',
    accessTime: '函館市電五稜郭公園前から徒歩15分'
  },
  {
    id: 'hakodate-morning-market',
    name: '函館朝市',
    nameEn: 'Hakodate Morning Market',
    region: 'donan',
    area: '函館',
    categories: ['food', 'city'],
    icon: 'crab',
    color: '#FFE5B4',
    description: '新鮮な海の幸が並ぶ活気あふれる市場。海鮮丼やイカ釣り体験が人気。',
    bestSeason: '通年',
    accessTime: 'JR函館駅から徒歩1分'
  },
  {
    id: 'motomachi',
    name: '元町エリア',
    nameEn: 'Motomachi Area',
    region: 'donan',
    area: '函館',
    categories: ['culture', 'city'],
    icon: 'church',
    color: '#FFD6E0',
    description: '異国情緒あふれる坂の街。教会やレトロな洋館が立ち並びフォトジェニック。',
    bestSeason: '通年',
    accessTime: '函館市電十字街から徒歩5分'
  },
  {
    id: 'kanemori-warehouse',
    name: '金森赤レンガ倉庫',
    nameEn: 'Kanemori Red Brick Warehouse',
    region: 'donan',
    area: '函館',
    categories: ['city', 'food'],
    icon: 'warehouse',
    color: '#FFE5B4',
    description: 'ベイエリアに佇む明治期のレンガ倉庫群。ショッピングやグルメが楽しめます。',
    bestSeason: '通年',
    accessTime: '函館市電十字街から徒歩5分'
  },
  {
    id: 'yunokawa-onsen',
    name: '湯の川温泉',
    nameEn: 'Yunokawa Onsen',
    region: 'donan',
    area: '函館',
    categories: ['hotspring'],
    icon: 'onsen',
    color: '#FFD6E0',
    description: '函館の奥座敷。津軽海峡を眺めながら浸かれる海辺の温泉郷。',
    bestSeason: '通年',
    accessTime: '函館市電湯の川温泉から徒歩5分'
  },
  {
    id: 'onuma-park',
    name: '大沼国定公園',
    nameEn: 'Onuma Quasi-National Park',
    region: 'donan',
    area: '七飯',
    categories: ['nature'],
    icon: 'lake',
    color: '#B5E2C5',
    description: '駒ヶ岳を背景にした湖沼群が美しい公園。サイクリングやボート遊びが楽しめます。',
    bestSeason: '春〜秋',
    accessTime: 'JR大沼公園駅から徒歩5分'
  },
  {
    id: 'matsumae-castle',
    name: '松前城',
    nameEn: 'Matsumae Castle',
    region: 'donan',
    area: '松前',
    categories: ['culture', 'season'],
    icon: 'castle',
    color: '#FFD6E0',
    description: '日本最北の城下町。約250種・1万本の桜が咲く北の桜の名所。',
    bestSeason: '春',
    accessTime: '函館から車で約2時間'
  },
  {
    id: 'esashi',
    name: '江差',
    nameEn: 'Esashi',
    region: 'donan',
    area: '江差',
    categories: ['culture'],
    icon: 'ship',
    color: '#B8E0F5',
    description: 'ニシン漁で栄えた港町。古い町並みと江差追分の伝統文化が残る。',
    bestSeason: '通年',
    accessTime: '函館から車で約1時間30分'
  },
  {
    id: 'trappistine',
    name: 'トラピスチヌ修道院',
    nameEn: 'Trappistine Monastery',
    region: 'donan',
    area: '函館',
    categories: ['culture'],
    icon: 'church',
    color: '#FFD6E0',
    description: '日本初の女子観想修道院。レンガ造りの優雅な建物と修道院クッキーが人気。',
    bestSeason: '通年',
    accessTime: 'JR函館駅からバス約30分'
  },

  // ===== 道東 (Doto) =====
  {
    id: 'kushiro-wetland',
    name: '釧路湿原',
    nameEn: 'Kushiro Wetland',
    region: 'doto',
    area: '釧路',
    categories: ['nature'],
    icon: 'crane',
    color: '#B5E2C5',
    description: '日本最大の湿原。タンチョウヅルの生息地として知られるラムサール条約登録地。',
    bestSeason: '通年',
    accessTime: 'JR釧路駅から車で約30分'
  },
  {
    id: 'lake-akan',
    name: '阿寒湖',
    nameEn: 'Lake Akan',
    region: 'doto',
    area: '釧路',
    categories: ['nature', 'hotspring'],
    icon: 'lake',
    color: '#B8E0F5',
    description: 'マリモが生息する神秘の湖。アイヌコタンの文化と温泉が楽しめる癒しのスポット。',
    bestSeason: '通年',
    accessTime: 'JR釧路駅からバス約2時間'
  },
  {
    id: 'lake-mashu',
    name: '摩周湖',
    nameEn: 'Lake Mashu',
    region: 'doto',
    area: '弟子屈',
    categories: ['nature'],
    icon: 'lake',
    color: '#D5C5E8',
    description: '世界屈指の透明度を誇る神秘の湖。「霧の摩周湖」と呼ばれる幻想的な景色。',
    bestSeason: '夏',
    accessTime: 'JR摩周駅から車で約20分'
  },
  {
    id: 'lake-kussharo',
    name: '屈斜路湖',
    nameEn: 'Lake Kussharo',
    region: 'doto',
    area: '弟子屈',
    categories: ['nature', 'hotspring'],
    icon: 'lake',
    color: '#B8E0F5',
    description: '日本最大のカルデラ湖。湖畔の砂を掘ると温泉が湧く砂湯が名物。',
    bestSeason: '春〜秋',
    accessTime: 'JR川湯温泉駅から車で約20分'
  },
  {
    id: 'shiretoko',
    name: '知床',
    nameEn: 'Shiretoko',
    region: 'doto',
    area: '斜里',
    categories: ['nature'],
    icon: 'forest',
    color: '#B5E2C5',
    description: '世界自然遺産に登録された手つかずの大自然。ヒグマやエゾシカに出会える秘境。',
    bestSeason: '夏〜秋',
    accessTime: 'JR知床斜里駅からバス約50分'
  },
  {
    id: 'shiretoko-goko',
    name: '知床五湖',
    nameEn: 'Shiretoko Five Lakes',
    region: 'doto',
    area: '斜里',
    categories: ['nature'],
    icon: 'forest',
    color: '#B5E2C5',
    description: '原生林の中に点在する5つの湖。高架木道から知床連山と湖を一望できます。',
    bestSeason: '夏',
    accessTime: 'ウトロ温泉から車で約20分'
  },
  {
    id: 'oshinkoshin-falls',
    name: 'オシンコシンの滝',
    nameEn: 'Oshinkoshin Falls',
    region: 'doto',
    area: '斜里',
    categories: ['nature'],
    icon: 'waterfall',
    color: '#B8E0F5',
    description: '「日本の滝百選」に選ばれた知床を代表する滝。二筋に分かれて流れる姿が美しい。',
    bestSeason: '通年',
    accessTime: 'JR知床斜里駅から車で約30分'
  },
  {
    id: 'abashiri-drift-ice',
    name: '網走の流氷',
    nameEn: 'Abashiri Drift Ice',
    region: 'doto',
    area: '網走',
    categories: ['season', 'nature'],
    icon: 'iceberg',
    color: '#B8E0F5',
    description: '冬の風物詩。流氷砕氷船「おーろら」に乗って大自然の神秘を体験できます。',
    bestSeason: '冬',
    accessTime: 'JR網走駅からバス約10分'
  },
  {
    id: 'abashiri-prison',
    name: '博物館 網走監獄',
    nameEn: 'Abashiri Prison Museum',
    region: 'doto',
    area: '網走',
    categories: ['culture'],
    icon: 'building',
    color: '#FFE5B4',
    description: '明治時代の監獄を移築復元した野外博物館。北海道開拓の歴史を学べます。',
    bestSeason: '通年',
    accessTime: 'JR網走駅からバス約10分'
  },
  {
    id: 'tokachi',
    name: '十勝平野',
    nameEn: 'Tokachi Plain',
    region: 'doto',
    area: '帯広',
    categories: ['nature', 'food'],
    icon: 'farm',
    color: '#FFE5B4',
    description: '広大な農地と牧場が広がる食の宝庫。豚丼や乳製品など絶品グルメも豊富。',
    bestSeason: '通年',
    accessTime: 'JR帯広駅周辺'
  },
  {
    id: 'lake-shikaribetsu',
    name: '然別湖',
    nameEn: 'Lake Shikaribetsu',
    region: 'doto',
    area: '鹿追',
    categories: ['nature', 'hotspring'],
    icon: 'lake',
    color: '#B8E0F5',
    description: '北海道で最も高所にある湖。冬季限定の氷上イグルー村「コタン」が幻想的。',
    bestSeason: '通年',
    accessTime: 'JR帯広駅から車で約1時間30分'
  },
  {
    id: 'nosappu-misaki',
    name: '納沙布岬',
    nameEn: 'Nosappu Cape',
    region: 'doto',
    area: '根室',
    categories: ['nature'],
    icon: 'lighthouse',
    color: '#B8E0F5',
    description: '北海道本土最東端の岬。日本一早い日の出と北方領土を望む景勝地。',
    bestSeason: '通年',
    accessTime: 'JR根室駅からバス約45分'
  },
  {
    id: 'kiritappu-wetland',
    name: '霧多布湿原',
    nameEn: 'Kiritappu Wetland',
    region: 'doto',
    area: '浜中',
    categories: ['nature'],
    icon: 'flower',
    color: '#D5C5E8',
    description: '花の湿原と呼ばれる広大な湿地。夏には色とりどりの花々が咲き乱れます。',
    bestSeason: '夏',
    accessTime: 'JR厚岸駅から車で約30分'
  },
  {
    id: 'mashu-onsen',
    name: '川湯温泉',
    nameEn: 'Kawayu Onsen',
    region: 'doto',
    area: '弟子屈',
    categories: ['hotspring'],
    icon: 'onsen',
    color: '#FFD6E0',
    description: '硫黄山のふもとに湧く強酸性の温泉。豊富な湯量で源泉かけ流しを満喫。',
    bestSeason: '通年',
    accessTime: 'JR川湯温泉駅から車で約10分'
  },
  {
    id: 'erimo-misaki',
    name: '襟裳岬',
    nameEn: 'Erimo Cape',
    region: 'doto',
    area: 'えりも',
    categories: ['nature'],
    icon: 'lighthouse',
    color: '#B8E0F5',
    description: '日高山脈が海に没する地点に位置する岬。アザラシの生息地としても知られます。',
    bestSeason: '春〜秋',
    accessTime: 'JR様似駅からバス約1時間'
  },

  // ===== 道北 (Dohoku) =====
  {
    id: 'asahiyama-zoo',
    name: '旭山動物園',
    nameEn: 'Asahiyama Zoo',
    region: 'dohoku',
    area: '旭川',
    categories: ['city'],
    icon: 'penguin',
    color: '#B8E0F5',
    description: '行動展示で日本一有名な動物園。ペンギンの散歩やホッキョクグマの泳ぐ姿は必見。',
    bestSeason: '通年',
    accessTime: 'JR旭川駅からバス約40分'
  },
  {
    id: 'asahikawa-ramen',
    name: '旭川ラーメン村',
    nameEn: 'Asahikawa Ramen Village',
    region: 'dohoku',
    area: '旭川',
    categories: ['food'],
    icon: 'ramen',
    color: '#FFE5B4',
    description: '旭川の人気ラーメン店が集結。醤油ベースの濃厚スープが特徴の旭川ラーメンを満喫。',
    bestSeason: '通年',
    accessTime: 'JR旭川駅からバス約20分'
  },
  {
    id: 'sounkyo',
    name: '層雲峡',
    nameEn: 'Sounkyo Gorge',
    region: 'dohoku',
    area: '上川',
    categories: ['nature', 'hotspring', 'season'],
    icon: 'cliff',
    color: '#B5E2C5',
    description: '24kmにわたる断崖絶壁の峡谷。紅葉と銀河の滝・流星の滝が絶景。',
    bestSeason: '秋',
    accessTime: 'JR上川駅からバス約30分'
  },
  {
    id: 'daisetsuzan',
    name: '大雪山',
    nameEn: 'Daisetsuzan',
    region: 'dohoku',
    area: '上川',
    categories: ['nature', 'season'],
    icon: 'mountain',
    color: '#B5E2C5',
    description: '日本最大の国立公園。日本で最も早い紅葉が見られる「神々の遊ぶ庭」。',
    bestSeason: '夏〜秋',
    accessTime: '旭川から車で約2時間'
  },
  {
    id: 'cape-soya',
    name: '宗谷岬',
    nameEn: 'Cape Soya',
    region: 'dohoku',
    area: '稚内',
    categories: ['nature'],
    icon: 'lighthouse',
    color: '#B8E0F5',
    description: '日本最北端の地。晴れた日にはサハリンを望むことができる感動のスポット。',
    bestSeason: '春〜秋',
    accessTime: 'JR稚内駅からバス約50分'
  },
  {
    id: 'wakkanai',
    name: '稚内',
    nameEn: 'Wakkanai',
    region: 'dohoku',
    area: '稚内',
    categories: ['city', 'food'],
    icon: 'lighthouse',
    color: '#B8E0F5',
    description: '日本最北の街。新鮮なウニや毛ガニなど海の幸が豊富で、ノシャップ岬の夕日も美しい。',
    bestSeason: '夏',
    accessTime: 'JR稚内駅'
  },
  {
    id: 'rishiri-island',
    name: '利尻島',
    nameEn: 'Rishiri Island',
    region: 'dohoku',
    area: '利尻',
    categories: ['nature'],
    icon: 'mountain',
    color: '#B5E2C5',
    description: '海に浮かぶ「利尻富士」の異名を持つ独立峰。高山植物と海岸線が美しい島。',
    bestSeason: '夏',
    accessTime: '稚内からフェリー約1時間40分'
  },
  {
    id: 'rebun-island',
    name: '礼文島',
    nameEn: 'Rebun Island',
    region: 'dohoku',
    area: '礼文',
    categories: ['nature', 'season'],
    icon: 'flower',
    color: '#D5C5E8',
    description: '日本最北の有人島。300種を超える高山植物が低地で見られる「花の浮島」。',
    bestSeason: '初夏',
    accessTime: '稚内からフェリー約1時間55分'
  },
  {
    id: 'sarobetsu',
    name: 'サロベツ原野',
    nameEn: 'Sarobetsu Plain',
    region: 'dohoku',
    area: '豊富',
    categories: ['nature'],
    icon: 'flower',
    color: '#D5C5E8',
    description: '日本三大湿原の一つ。エゾカンゾウなどの花々と利尻富士の眺望が見事。',
    bestSeason: '夏',
    accessTime: 'JR豊富駅から車で約15分'
  },
  {
    id: 'biei-hill',
    name: '四季彩の丘',
    nameEn: 'Shikisai-no-Oka',
    region: 'doo',
    area: '美瑛',
    categories: ['nature', 'season'],
    icon: 'flower',
    color: '#D5C5E8',
    description: '虹のように色とりどりの花畑が広がる丘。アルパカ牧場も併設されています。',
    bestSeason: '夏〜秋',
    accessTime: 'JR美馬牛駅から徒歩約25分'
  },
  {
    id: 'tomamu',
    name: '星野リゾート トマム',
    nameEn: 'Hoshino Resorts Tomamu',
    region: 'doo',
    area: '占冠',
    categories: ['nature', 'season'],
    icon: 'cloud',
    color: '#D5C5E8',
    description: '雲海テラスで有名なリゾート。冬は氷の街「アイスヴィレッジ」も楽しめます。',
    bestSeason: '通年',
    accessTime: 'JRトマム駅から送迎バス約5分'
  },
  {
    id: 'sapporo-beer',
    name: 'サッポロビール博物館',
    nameEn: 'Sapporo Beer Museum',
    region: 'doo',
    area: '札幌',
    categories: ['food', 'culture'],
    icon: 'bottle',
    color: '#FFE5B4',
    description: '日本唯一のビール博物館。明治から続くビール造りの歴史を学び、試飲も可能。',
    bestSeason: '通年',
    accessTime: 'JR札幌駅からバス約10分'
  },
  {
    id: 'noboribetsu-bear',
    name: 'のぼりべつクマ牧場',
    nameEn: 'Noboribetsu Bear Park',
    region: 'doo',
    area: '登別',
    categories: ['city', 'nature'],
    icon: 'bear',
    color: '#FFE5B4',
    description: '約70頭のヒグマを間近で観察できる牧場。ロープウェイで山頂へアクセス。',
    bestSeason: '通年',
    accessTime: '登別温泉バスターミナルから徒歩10分'
  },
  {
    id: 'rusutsu',
    name: 'ルスツリゾート',
    nameEn: 'Rusutsu Resort',
    region: 'doo',
    area: 'ルスツ',
    categories: ['nature', 'season'],
    icon: 'mountain',
    color: '#B8E0F5',
    description: '北海道最大級の遊園地とスキーリゾートを併せ持つ複合リゾート。',
    bestSeason: '通年',
    accessTime: '札幌から車で約90分'
  },
  {
    id: 'tomita-melon',
    name: '富良野メロン',
    nameEn: 'Furano Melon Farms',
    region: 'doo',
    area: '富良野',
    categories: ['food', 'season'],
    icon: 'melon',
    color: '#B5E2C5',
    description: '夏の風物詩。糖度抜群の赤肉メロンを産地で味わう贅沢な体験。',
    bestSeason: '夏',
    accessTime: 'JR富良野駅周辺'
  },
  {
    id: 'jozankei-onsen',
    name: '定山渓温泉',
    nameEn: 'Jozankei Onsen',
    region: 'doo',
    area: '札幌',
    categories: ['hotspring', 'season'],
    icon: 'onsen',
    color: '#FFD6E0',
    description: '札幌の奥座敷と呼ばれる渓谷の温泉郷。秋の紅葉が特に美しい。',
    bestSeason: '秋',
    accessTime: 'JR札幌駅からバス約70分'
  },
  {
    id: 'shakotan',
    name: '積丹半島',
    nameEn: 'Shakotan Peninsula',
    region: 'doo',
    area: '積丹',
    categories: ['nature', 'food'],
    icon: 'sea',
    color: '#B8E0F5',
    description: '「積丹ブルー」と呼ばれる青い海と神威岬の絶景。夏のウニ漁も名物。',
    bestSeason: '夏',
    accessTime: '小樽から車で約1時間30分'
  }
];

const REGIONS = {
  doo:    { name: '道央',   nameEn: 'Central',  color: '#FFD6E0', icon: 'sakura' },
  donan:  { name: '道南',   nameEn: 'Southern', color: '#FFE5B4', icon: 'castle' },
  doto:   { name: '道東',   nameEn: 'Eastern',  color: '#B5E2C5', icon: 'crane' },
  dohoku: { name: '道北',   nameEn: 'Northern', color: '#B8E0F5', icon: 'snowflake' }
};

const CATEGORIES = {
  nature:    { name: '自然',     emoji: '🌳' },
  city:      { name: '街・施設', emoji: '🏙️' },
  hotspring: { name: '温泉',     emoji: '♨️' },
  food:      { name: 'グルメ',   emoji: '🍜' },
  culture:   { name: '文化・歴史', emoji: '🏯' },
  season:    { name: '季節',     emoji: '🌸' }
};

if (typeof module !== 'undefined') {
  module.exports = { SPOTS, REGIONS, CATEGORIES };
}
